### ISSUE TITLE
About building a docker for ReMon

### ISSUE THREAD

**Issue by SchordingersDogCat** [ReMon-MVEE/ReMon#7]
Hi Stijn,

The GHUMVEE requires a lot of libraries, some of which are very old and difficult to configure. 

Is it possible for setting up a docker from your side?

Regards,
Junchao

**Comment by bcoppens** [comment]
Hi Junchao,

In the meantime we support some more recent libraries and kernels (Ubuntu 18.04 and 20.04 should now just work). In addition, we also created a Dockerfile, and a created a `docker_MVEE.sh` script that does some additional steps to set up that docker environment. I hope these are helpful for you! If this script or the Dockerfile don't work, please let us know!

Apologies for the delay by the way, but we only recently made this additional support and tooling public. (And moved this repo to a new GitHub organization, as you might have noticed, and its due to that move that I even noticed your issue in the first place, as I was not watching Stijn's original repository for issues.)

Best regards,
Bart
